import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { FlowEvents } from './FlowEvents';
import { getFlowEvents } from '../lib/tauri';
import type { FlowPage } from '../types';
vi.mock('../lib/tauri', () => ({ getFlowEvents: vi.fn() }));
afterEach(() => { cleanup(); vi.resetAllMocks(); });
const page: FlowPage = { available: true, frameIndex: 0, endFrameIndex: 1, flowId: null, total: 2, nextStart: 1, unknownTypes: 0, beginCount: 1, endCount: 1, scope: '窗口并非完整链路', rows: [{frameIndex: 0, threadIndex: 1, threadId: '42', thread: 'Worker', eventIndex: 0, sampleIndex: 3, flowId: 4294967295, eventType: 1, kind: 'ParallelNext', marker: 'Job', sampleStartNs: '18446744073709551615', sampleDurationMs: 1}] };
it('filters explicit window and ID, preserves pagination and unavailable semantics', async () => {
  vi.mocked(getFlowEvents).mockResolvedValue(page);
  render(<FlowEvents fileId="a" frame={0} frames={[{frameIndex:0},{frameIndex:1},{frameIndex:8}]} />);
  fireEvent.click(screen.getByText('Flow 跨线程事件'));
  expect(screen.queryByRole('option', {name:'8'})).not.toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Flow 结束帧'), {target:{value:'1'}});
  fireEvent.click(screen.getByText('读取 Flow'));
  await screen.findByText('ParallelNext (1)');
  fireEvent.click(screen.getByText('下一页 Flow'));
  await waitFor(() => expect(getFlowEvents).toHaveBeenLastCalledWith('a',0,1,null,1));
  await waitFor(() => expect(screen.getByText('4294967295')).not.toBeDisabled());
  fireEvent.click(screen.getByText('4294967295'));
  fireEvent.click(screen.getByText('读取 Flow'));
  await waitFor(() => expect(getFlowEvents).toHaveBeenLastCalledWith('a',0,1,4294967295,0));
  await waitFor(() => expect(screen.getByText('读取 Flow')).not.toBeDisabled());
  vi.mocked(getFlowEvents).mockResolvedValue({...page,available:false,rows:[],total:0,nextStart:null});
  fireEvent.click(screen.getByText('读取 Flow'));
  await screen.findByText(/不可用：该输入未提供 Flow/);
});
it('rejects invalid ID and ignores delayed results after recording switch', async () => {
  let resolve!: (v:FlowPage)=>void;
  vi.mocked(getFlowEvents).mockImplementation(() => new Promise(r=>{resolve=r;}));
  const app=render(<FlowEvents key="a" fileId="a" frame={0} frames={[{frameIndex:0}]} />);
  fireEvent.change(screen.getByLabelText('Flow ID'),{target:{value:'4294967296'}});
  fireEvent.click(screen.getByText('读取 Flow'));
  expect(getFlowEvents).not.toHaveBeenCalled();
  expect(screen.getByRole('alert')).toHaveTextContent('整数');
  fireEvent.change(screen.getByLabelText('Flow ID'),{target:{value:''}});
  fireEvent.click(screen.getByText('读取 Flow'));
  app.rerender(<FlowEvents key="b" fileId="b" frame={0} frames={[{frameIndex:0}]} />);
  resolve(page);
  await waitFor(() => expect(screen.queryByText('ParallelNext (1)')).not.toBeInTheDocument());
});
