import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { open, save } from '@tauri-apps/plugin-dialog';
import type { DiagnoseState } from '../hooks/useDiagnose';
import type { AgentPreset } from '../types';
import './OptimizationPanel.css';
import { DiagnosisStream } from './DiagnosisStream';
import type { Conditions, Run, Project, HotspotPage, Statistic } from '../types/optimization';
export const emptyConditions = ():Conditions => ({device:'',platform:'',scenario:'',operation:'',build:'',quality:'',resolution:'',profiling:'',codeVersion:''});
const statuses:Record<string,string>={running:'进行中',modified:'已修改',partial:'部分完成',failed:'失败',rolled_back:'已回退',interrupted:'已中断',passed:'通过',unavailable:'无法完成',applied:'已应用',prepared:'待核对',not_applied:'未应用',conflict:'存在冲突',pending:'待确认',accepted:'已接受',continue:'继续调查',investigated:'已调查，暂未修改'};
const metricLabels:Record<string,string>={cpuMs:'主线程 CPU（ms）',frameMs:'录制帧时间（ms）',gcBytes:'GC 分配（B/帧）','Draw Calls Count':'Draw Call/帧','SetPass Calls Count':'SetPass/帧','Batches Count':'Batch/帧','Triangles Count':'三角形/帧','Vertices Count':'顶点/帧'};
const statusLabel=(s:string)=>statuses[s]??s;
const conditionLabels:Record<keyof Conditions,string>={device:'设备',platform:'平台',scenario:'场景',operation:'复现操作',build:'构建类型',quality:'画质',resolution:'分辨率',profiling:'Profiler 设置',codeVersion:'代码版本'};
export function modificationAvailability(agent:AgentPreset):string|null {return !agent.available?'未检测到此 AI 程序':!['codex','claude-code'].includes(agent.id)?'尚未验证此 AI 的修改能力':null;}
function range(s:string):[number,number]|null {if(!s.trim())return null;const n=s.split('-').map(Number);if(n.length!==2||n.some(v=>!Number.isSafeInteger(v)||v<0)||n[0]>n[1])throw Error('帧范围格式：起始帧-结束帧');return [n[0],n[1]];}
export function OptimizationPanel({state,onOpenCapture}:{state:DiagnoseState;onOpenCapture?:(path:string)=>void}) {
 const [project,setProject]=useState<Project|null>(null),[visible,setVisible]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const [statistic,setStatistic]=useState<Statistic>('p95');
 const [roundId,setRoundId]=useState(''),[agent,setAgent]=useState(''),[tests,setTests]=useState(''),[requirements,setRequirements]=useState(''),[useSaved,setUseSaved]=useState(false);
 const [conditions,setConditions]=useState<Record<string,Conditions>>({}),[budgets,setBudgets]=useState<Record<string,number>>({});
 const [candidate,setCandidate]=useState(''),[aRange,setARange]=useState(''),[bRange,setBRange]=useState(''),[confirmed,setConfirmed]=useState(false),[detail,setDetail]=useState('');
 const [detailPage,setDetailPage]=useState<{run:Run;start:number;next:number|null}|null>(null);
 const [hotspots,setHotspots]=useState<HotspotPage|null>(null),[nextBaseline,setNextBaseline]=useState('');
 const round=project?.rounds.find(r=>r.id===roundId)??project?.rounds.at(-1);
 const busy=loading||!!project?.busy||state.phase==='diagnosing'||state.phase==='preparing';
 async function call(action:Record<string,unknown>){setError('');setLoading(true);try{const next=await invoke<Project|null>('optimization_command',{action});setProject(next);return next;}catch(e){setError(String(e));return undefined;}finally{setLoading(false);}}
 useEffect(()=>{invoke<Project|null>('optimization_command',{action:{op:'get'}}).then(setProject).catch(()=>{});},[]);
 useEffect(()=>{if(!project||!visible)return;let live=true;const timer=setInterval(()=>{invoke<Project>('optimization_command',{action:{op:'get'}}).then(p=>{if(live)setProject(p);}).catch(e=>{if(live)setError(String(e));});},1500);return()=>{live=false;clearInterval(timer);};},[project?.id,visible]);
 useEffect(()=>{if(!round)return;setTests(round.tests.join('\n'));setAgent(current=>current||round.reports.find(r=>r.stage==='project')?.agentId||'');setDetail('');},[round?.id]);
 useEffect(()=>{setHotspots(round?.comparison?.hotspots??null);},[round?.id,round?.comparison?.baseline,round?.comparison?.candidate]);
 useEffect(()=>{setConditions(Object.fromEntries((project?.captures??[]).map(c=>[c.id,c.conditions])));setBudgets(project?.budgets??{});setCandidate('');setNextBaseline('');},[project?.id]);
 async function openProject(){try{const directory=await open({directory:true,title:'打开含 optimization.json 的保存目录'});if(typeof directory==='string'){const p=await call({op:'open',directory});if(p){setUseSaved(true);setAgent(p.rounds.at(-1)?.reports.find(r=>r.stage==='project')?.agentId??'');}}}catch(e){setError(String(e));}}
 const currentReport=state.reports.filter(r=>r.stage==='project'&&r.status==='completed').at(-1);
 useEffect(()=>{if(currentReport){setAgent(currentReport.agentId);setVisible(true);setUseSaved(false);}},[currentReport?.reportId]);
 async function update(){if(!round)return;return call({op:'update',roundId:round.id,tasks:round.tasks,budgets,conditions,tests:tests.split('\n').map(t=>t.trim()).filter(Boolean)});}
 async function start(){
  if(!agent)return;
  let target=round;
  if(currentReport&&!useSaved&&state.upload){const p=await call({op:'prepareAutomatic',fileId:state.upload.fileId});if(!p)return;target=p.rounds.at(-1);if(target)setRoundId(target.id);}
  if(target)await call({op:'startAutomatic',roundId:target.id,agentId:agent,requirements});
 }
 async function importB(){try{const path=await open({multiple:false,title:'选择修改后重录的 B',filters:[{name:'Profiler',extensions:['data','json']}]});if(typeof path!=='string')return;const p=await call({op:'import',path,conditions:emptyConditions()});if(p){setCandidate(p.captures.at(-1)!.id);setConfirmed(false);}}catch(e){setError(String(e));}}
 async function compare(){if(!round)return;try{const rangeA=range(aRange),rangeB=range(bRange);if(await update()){const p=await call({op:'compare',roundId:round.id,candidateId:candidate,rangeA,rangeB,confirmed});if(p)setHotspots(p.rounds.find(r=>r.id===round.id)?.comparison?.hotspots??null);}}catch(e){setError(String(e));}}
 async function exportRecord(format:string){try{const path=await save({defaultPath:`optimization.${format==='html'?'html':'md'}`});if(path)await call({op:'export',path,format});}catch(e){setError(String(e));}}
 async function showDetail(run:Run,start=0){if(!round)return;try{const page=await invoke<{text:string;nextStart:number|null}>('optimization_command',{action:{op:'detail',roundId:round.id,runId:run.id,start}});setDetail(page.text);setDetailPage({run,start,next:page.nextStart});}catch(e){setError(String(e));}}

 return <section className="optimization"><button className="btn" onClick={()=>setVisible(!visible)}>{visible?'收起':'打开'}优化项目 · 修改与 A/B 复验{project?.busy?'（修改运行中）':''}</button>
 {visible&&<><p>AI 会根据诊断和定位继续调查、修改或新增代码，并保存可回退记录。完成后请重新录制，确认性能和玩法。</p>{error&&<div role="alert" className="error-banner">{error}</div>}
 <p>工程：{(useSaved?project?.root:state.projectInfo?.root??project?.root)??'请先完成工程定位'}</p>
 <label>修改 AI<select value={agent} disabled={busy} onChange={e=>setAgent(e.target.value)}><option value="">请选择</option>{state.agents.map(a=><option key={a.id} value={a.id} disabled={!!modificationAvailability(a)}>{a.label}{modificationAvailability(a)?` · ${modificationAvailability(a)}`:''}</option>)}</select></label>
 <label>补充要求（选填）<textarea disabled={busy} placeholder="例如：保持玩法不变，优先减少卡顿" value={requirements} onChange={e=>setRequirements(e.target.value)}/></label>
 <div className="optimization-actions"><button className="btn btn-primary" disabled={busy||!agent||(useSaved?!round?.reports.some(r=>r.stage==='project'):!currentReport&&!round?.reports.some(r=>r.stage==='project'))||!!modificationAvailability(state.agents.find(a=>a.id===agent)??{id:agent,label:'',command:'',args:[],available:false})} onClick={start}>开始优化</button>{project?.busy&&<button className="btn" onClick={()=>call({op:'cancel'})}>停止优化（保留已有修改）</button>}</div>
 {project?.busy&&<p role="status">AI 正在调查、优化和检查，请稍候。可以随时停止。</p>}
 <details><summary>打开或管理优化记录</summary>{!project?<button className="btn" disabled={busy} onClick={openProject}>打开优化项目</button>:<><p>自动保存在 {project.directory}</p><button className="btn" disabled={busy} onClick={()=>call({op:'close'})}>关闭项目</button></>}</details>
 {project&&<>
 <div className="optimization-actions"><button className="btn" disabled={busy} onClick={()=>exportRecord('markdown')}>导出 Markdown</button><button className="btn" disabled={busy} onClick={()=>exportRecord('html')}>导出 HTML</button></div>
 {project.rounds.length>0&&<label>轮次<select value={round?.id??''} disabled={busy} onChange={e=>{setRoundId(e.target.value);setUseSaved(true);setConfirmed(false);}}>{project.rounds.map((r,i)=><option key={r.id} value={r.id}>第 {i+1} 轮 · {statusLabel(r.decision)}</option>)}</select></label>}
 {round&&<>
 <details><summary>检查选项（可选）</summary><label>EditMode 测试完整名称（留空仅编译检查）<textarea disabled={busy} value={tests} onChange={e=>setTests(e.target.value)}/></label><button className="btn" disabled={busy} onClick={update}>保存检查选项</button></details>
 {round.runs.at(-1)&&<div className="optimization-result"><p>本轮结果：{statusLabel(round.runs.at(-1)!.status)}</p><p>已记录 {round.runs.at(-1)!.changes.filter(c=>!c.path.endsWith('.meta')&&c.kind!=='directory').length} 次代码变化。{round.runs.at(-1)!.checks.length?`检查：${statusLabel(round.runs.at(-1)!.checks.at(-1)!.status)}`:'尚未完成编译检查'}</p>{round.runs.at(-1)!.tasks?.some(t=>t.kind==='marker')&&<p>已安排补充采样，需要重新录制确认。</p>}<p>{round.runs.at(-1)!.reason}</p><DiagnosisStream text={round.runs.at(-1)!.text??''} isStreaming={!!project.busy}/>{round.runs.at(-1)!.textPartial&&<p>此处为报告预览，可导出完整报告。</p>}</div>}
 {round.runs.map(run=><details key={run.id}><summary>查看详细记录 · {run.agentId} · {statusLabel(run.status)}</summary><p>{run.automatic?'AI 自主优化':'原范围修改'} · 新会话 {run.sessionId} · {run.reason}</p><p>{run.tasks?.map(t=>t.title).join('；')}</p><pre>{run.text}</pre>{run.textPartial&&<p>此处为正文预览，完整内容请查看完整修改记录或导出。</p>}<ul>{run.changes.map((c,i)=><li key={i}>{c.path} · {statusLabel(c.state)}</li>)}</ul><p>检查结果：{run.checks.length?run.checks.map((c,i)=>`第 ${i+1} 次：${statusLabel(c.status)}${c.reason?`（${c.reason}）`:''}`).join('；'):'尚未检查'}</p><button className="btn" disabled={busy} onClick={()=>showDetail(run)}>查看完整修改记录</button></details>)}{detail&&detailPage&&<><p>完整修改记录 · 从字符 {detailPage.start} 起{detailPage.next!=null?'（本页不是全文）':'（最后一页）'}</p><pre className="optimization-detail">{detail}</pre>{detailPage.start>0&&<button className="btn" onClick={()=>showDetail(detailPage.run,Math.max(0,detailPage.start-12000))}>上一页记录</button>}{detailPage.next!=null&&<button className="btn" onClick={()=>showDetail(detailPage.run,detailPage.next!)}>下一页记录</button>}</>}
 {round.runs.length>0&&<button className="btn" disabled={busy||round.runs.at(-1)!.checks.length>=3||round.runs.at(-1)!.status==='rolled_back'} onClick={async()=>{if(await update())await call({op:'check',roundId:round.id});}}>重新执行 Unity 检查（本次运行最多 3 次）</button>}<details><summary>下一步：导入新录制，比较效果</summary><h3>重新录制，检查效果</h3><p>性能状态：{round.performanceStatus??'待录制'} · 玩法正确性：{statusLabel(round.correctness)}</p>{round.tasks.filter(t=>t.selected).map(t=><label key={t.id}>{t.kind==='marker'?'新采样是否回答调查问题':'任务目标与行为验收'}：{t.title}<select disabled={busy} value={round.taskVerifications?.[t.id]??'pending'} onChange={e=>call({op:'verifyTask',roundId:round.id,taskId:t.id,status:e.target.value})}><option value="pending">待核对</option><option value="passed">人工核对通过</option><option value="problem">仍有问题</option></select></label>)}<p>按相同设备、场景、操作、画质和 Profiler 设置重录。纯 Marker 任务检查新采样是否回答问题，不按性能下降判定完成。</p>
 <button className="btn" disabled={busy} onClick={importB}>导入重录 B</button><label>B 录制<select disabled={busy} value={candidate} onChange={e=>{setCandidate(e.target.value);setConfirmed(false);}}><option value="">请选择</option>{project.captures.filter(c=>c.id!==round.baseline).map(c=><option key={c.id} value={c.id}>{c.snapshot.fileName} · {c.snapshot.frameCount} 帧</option>)}</select></label>
 {onOpenCapture&&candidate&&<button className="btn" disabled={busy} onClick={()=>{const c=project.captures.find(c=>c.id===candidate);if(c)onOpenCapture(c.path);}}>在分析页打开 B，核对新 Marker</button>}{project.captures.filter(c=>c.id===round.baseline||c.id===candidate).map(c=><details key={c.id}><summary>{c.id===round.baseline?'A':'B'}：{c.snapshot.fileName} · 复现条件</summary><div className="optimization-conditions">{Object.entries(conditionLabels).map(([k,label])=><label key={k}>{label}<input disabled={busy} value={(conditions[c.id]??c.conditions)[k as keyof Conditions]} onChange={e=>{setConditions({...conditions,[c.id]:{...(conditions[c.id]??c.conditions),[k]:e.target.value}});setConfirmed(false);}}/></label>)}</div></details>)}
 <div className="optimization-conditions"><label>A 连续原始帧范围<input placeholder="留空表示整段，如 100-160" value={aRange} onChange={e=>setARange(e.target.value)}/></label><label>B 连续原始帧范围<input placeholder="独立选择，不与 A 帧号对齐" value={bRange} onChange={e=>setBRange(e.target.value)}/></label>{Object.keys(metricLabels).map(k=><label key={k}>{metricLabels[k]} 的 P95 预算<input type="number" min="0" value={budgets[k]??''} onChange={e=>setBudgets(b=>{const next={...b};if(e.target.value==='')delete next[k];else next[k]=Number(e.target.value);return next;})}/></label>)}</div><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>已核对复现条件；代码版本变化是本轮实验变量</label><button className="btn" disabled={busy||!candidate} onClick={compare}>比较 B − A</button>
 {round.comparison&&<><p>{round.comparison.comparability} · 未知：{round.comparison.unknown.join('、')||'无'} · 不同：{round.comparison.mismatch.join('、')||'无'}</p><label>分布统计<select value={statistic} onChange={e=>setStatistic(e.target.value as Statistic)}>{(['mean','p50','p95','p99','max'] as const).map(s=><option key={s} value={s}>{s.toUpperCase()}</option>)}</select></label><table><thead><tr><th>指标 {statistic.toUpperCase()}</th><th>A / 覆盖</th><th>B / 覆盖</th><th>B − A</th><th>P95 预算判定</th></tr></thead><tbody>{round.comparison.metrics.map(m=><tr key={m.metric}><td>{metricLabels[m.metric]??m.metric}</td><td>{m.a[statistic]??'—'} · {m.a.validFrames}/{m.a.totalFrames}</td><td>{m.b[statistic]??'—'} · {m.b.validFrames}/{m.b.totalFrames}</td><td>{m.delta[statistic].absolute??'—'} / {m.delta[statistic].percent?.toFixed(1)??'—'}%</td><td>{m.verdict}</td></tr>)}</tbody></table><p>{round.comparison.scope}</p>{hotspots?.rows&&<><h4>按线程角色与完整 Marker 路径关联（共 {hotspots.total} 项）</h4><table><thead><tr><th>角色 / 路径</th><th>A / B 平均 inclusive ms 每帧</th><th>差值 / 关联</th></tr></thead><tbody>{hotspots.rows.map((h,i)=><tr key={i}><td>{h.roleAndPath[1]} / {h.roleAndPath[2].join(' → ')}</td><td>{h.a?.inclusiveMsPerFrame.toFixed(3)??'—'} / {h.b?.inclusiveMsPerFrame.toFixed(3)??'—'}</td><td>{h.deltaInclusiveMsPerFrame?.toFixed(3)??'—'} · {h.association}</td></tr>)}</tbody></table>{hotspots.nextStart!=null&&<button className="btn" onClick={()=>invoke<HotspotPage>('optimization_command',{action:{op:'hotspots',roundId:round.id,start:hotspots.nextStart}}).then(setHotspots).catch(e=>setError(String(e)))}>下一页热点</button>}</>}{hotspots?.status==='unavailable'&&<p>热点关联不可用：{hotspots.reason}</p>}</>}
 <label>玩法正确性<select disabled={busy} value={round.correctness} onChange={e=>call({op:'decide',roundId:round.id,decision:round.decision,correctness:e.target.value})}><option value="pending">待确认</option><option value="passed">通过</option><option value="problem">存在问题</option></select></label><div className="optimization-actions"><button className="btn" disabled={busy} onClick={()=>call({op:'decide',roundId:round.id,decision:'accepted',correctness:round.correctness})}>接受本轮</button><button className="btn" disabled={busy||!round.runs.some(r=>r.changes.length)} onClick={()=>call({op:'rollback',roundId:round.id})}>回退本轮（冲突时停止）</button><label>下一轮基线<select value={nextBaseline} onChange={e=>setNextBaseline(e.target.value)}><option value="">明确选择一份录制</option>{project.captures.map(c=><option key={c.id} value={c.id}>{c.snapshot.fileName} · {c.id===round.baseline?'本轮 A':c.id===candidate?'本轮 B':'其他录制'}</option>)}</select></label><button className="btn" disabled={busy||!nextBaseline} onClick={async()=>{const p=await call({op:'next',baselineId:nextBaseline});if(p){setRoundId(p.rounds.at(-1)!.id);const capture=p.captures.find(c=>c.id===nextBaseline);if(capture&&onOpenCapture)onOpenCapture(capture.path);}}}>以选定基线开始下一轮</button></div>
 </details>
 <button className="btn" disabled={busy||!round.runs.some(r=>r.changes.some(c=>c.state!=='rolled_back'))} onClick={()=>call({op:'rollback',roundId:round.id})}>撤销本轮代码修改</button>
 </>}
 </>}
 </>}
 </section>;
}
